/*
 * Copyright 2002-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.aop;

import java.lang.reflect.Method;

/**
 * Part of a {@link Pointcut}: Checks whether the target method is eligible for advice.
 *
 * <p>A MethodMatcher may be evaluated <b>statically</b> or at <b>runtime</b> (dynamically).
 * Static matching involves method and (possibly) method attributes. Dynamic matching
 * also makes arguments for a particular call available, and any effects of running
 * previous advice applying to the joinpoint.
 *
 * <p>If an implementation returns {@code false} from its {@link #isRuntime()}
 * method, evaluation can be performed statically, and the result will be the same
 * for all invocations of this method, whatever their arguments. This means that
 * if the {@link #isRuntime()} method returns {@code false}, the 3-arg
 * {@link #matches(java.lang.reflect.Method, Class, Object[])} method will never be invoked.
 *
 * <p>If an implementation returns {@code true} from its 2-arg
 * {@link #matches(java.lang.reflect.Method, Class)} method and its {@link #isRuntime()} method
 * returns {@code true}, the 3-arg {@link #matches(java.lang.reflect.Method, Class, Object[])}
 * method will be invoked <i>immediately before each potential execution of the related advice</i>,
 * to decide whether the advice should run. All previous advice, such as earlier interceptors
 * in an interceptor chain, will have run, so any state changes they have produced in
 * parameters or ThreadLocal state will be available at the time of evaluation.
 *
 * <p>Concrete implementations of this interface typically should provide proper
 * implementations of {@link Object#equals(Object)} and {@link Object#hashCode()}
 * in order to allow the matcher to be used in caching scenarios &mdash; for
 * example, in proxies generated by CGLIB.
 *
 * @author Rod Johnson
 * @since 11.11.2003
 * @see Pointcut
 * @see ClassFilter
 */
// Pointcut ：检查目标方法是否有资格获得建议。
//
// MethodMatcher 可以静态评估或在运行时（动态）评估。 静态匹配涉及方法和（可能）方法属性。
// 动态匹配还使特定调用的参数可用，并且运行先前建议的任何效果都适用于连接点。
//
// 如果实现从其isRuntime()方法返回false ，则可以静态执行评估，并且对于此方法的所有调用，无论其参数如何，
// 结果都是相同的。 这意味着如果isRuntime()方法返回false ，则永远不会
// 调用 3-arg matches(Method, Class, Object[])方法。
//
// 如果实现返回true从其2- ARG matches(Method, Class)方法及其isRuntime()方法返回true ，
// 3-ARG matches(Method, Class, Object[])方法将被立即的每个电势执行之前调用相关的advice ，
// 决定advice是否应该运行。 所有先前的通知，例如拦截器链中的早期拦截器，都将运行，因此它们在参数
// 或 ThreadLocal 状态中产生的任何状态更改都将在评估时可用。
//
// 这个接口的具体实现通常应该提供Object.equals(Object)和Object.hashCode()正确实现，以便
// 允许在缓存场景中使用匹配器——例如，在由 CGLIB 生成的代理中。
//
// 方法匹配器：判断当前方法是不是符合条件的
public interface MethodMatcher {

	/**
	 * Perform static checking whether the given method matches.
	 * <p>If this returns {@code false} or if the {@link #isRuntime()}
	 * method returns {@code false}, no runtime check (i.e. no
	 * {@link #matches(java.lang.reflect.Method, Class, Object[])} call)
	 * will be made.
	 * @param method the candidate method
	 * @param targetClass the target class
	 * @return whether or not this method matches statically
	 */
	// 执行静态检查给定方法是否匹配。
	// 如果这返回false或isRuntime()方法返回false ，则不会进行运行时检查（即没有
	// matches(Method, Class, Object[])调用）。
	//
	// 方法和目标类是不是保持一致的
	//
	// 参形：
	//			方法——候选方法
	//			targetClass – 目标类
	// 返回值：
	//			此方法是否静态匹配
	boolean matches(Method method, Class<?> targetClass);

	/**
	 * Is this MethodMatcher dynamic, that is, must a final call be made on the
	 * {@link #matches(java.lang.reflect.Method, Class, Object[])} method at
	 * runtime even if the 2-arg matches method returns {@code true}?
	 * <p>Can be invoked when an AOP proxy is created, and need not be invoked
	 * again before each method invocation,
	 * @return whether or not a runtime match via the 3-arg
	 * {@link #matches(java.lang.reflect.Method, Class, Object[])} method
	 * is required if static matching passed
	 */
	// 这个 MethodMatcher 是否是动态的，也就是说，即使 2-arg 匹配方法返回true ，也必须在运行时
	// 对matches(Method, Class, Object[])方法进行最终调用？
	//
	// 可以在创建 AOP 代理时调用，无需在每次方法调用之前再次调用，
	// 判断当前方法是不是运行时的方法
	//
	// 返回值：
	//			如果通过了静态匹配，则是否需要通过 3-arg matches(Method, Class, Object[])方法进行运行时匹配
	//
	// 用 isRuntime() 来控制 matches(args),这两个方法是二选一的。
	boolean isRuntime();

	/**
	 * Check whether there a runtime (dynamic) match for this method,
	 * which must have matched statically.
	 * <p>This method is invoked only if the 2-arg matches method returns
	 * {@code true} for the given method and target class, and if the
	 * {@link #isRuntime()} method returns {@code true}. Invoked
	 * immediately before potential running of the advice, after any
	 * advice earlier in the advice chain has run.
	 * @param method the candidate method
	 * @param targetClass the target class
	 * @param args arguments to the method
	 * @return whether there's a runtime match
	 * @see MethodMatcher#matches(Method, Class)
	 */
	// 检查此方法是否存在运行时（动态）匹配，该匹配必须是静态匹配的。
	//
	// 调用此方法只有在2-ARG方法返回匹配true对于给定的方法和目标类，并且如果isRuntime()方法返回true 。
	// 在建议链中较早的任何建议运行之后，在建议可能运行之前立即调用。
	//
	// 参形：
	//			方法——候选方法
	//			targetClass – 目标类
	//			args – 方法的参数
	// 返回值：
	//			是否存在运行时匹配
	boolean matches(Method method, Class<?> targetClass, Object... args);


	/**
	 * Canonical instance that matches all methods.
	 */
	// 匹配所有方法的规范实例。
	MethodMatcher TRUE = TrueMethodMatcher.INSTANCE;

}
